# Generated by Django 5.0.6 on 2024-07-04 16:03

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kanbanboard', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ticket',
            old_name='crated_by',
            new_name='created_by',
        ),
        migrations.AlterField(
            model_name='ticket',
            name='created_at',
            field=models.DateField(default=datetime.date.today),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='due_date',
            field=models.DateField(),
        ),
    ]
