# Generated by Django 5.0.6 on 2024-07-04 19:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kanbanboard', '0002_rename_crated_by_ticket_created_by_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='created_by_username',
            field=models.CharField(blank=True, max_length=150),
        ),
    ]
